# Generated by Django 2.1.2 on 2019-03-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='active1',
            field=models.BooleanField(default=True),
        ),
    ]
